import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// T048: Configure sidebars with 8-chapter navigation structure
// Use autogenerated sidebar for simplicity - Docusaurus will detect all docs
const sidebars: SidebarsConfig = {
  textbookSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
